logging:
  level: DEBUG
metadata:
  contact:
    city: Trondheim
    country: Norway
    email: francesco.frassinelli@nina.no
    hours: Mo-Fr 08:00-15:30
    instructions: During hours of service. Off on weekends.
    name: Francesco, Frassinelli
    position: Senior engineer IT
    role: pointOfContact
    stateorprovince: Administrative Area
    url: https://www.nina.no/english/Contact/Employees/Employee-info?AnsattID=15958
  identification:
    description:
      en: NINA catalog for NVDB data
    keywords:
      en:
      - NINA
      - NVDB
    terms_of_service: https://nvdbapiles-v3.atlas.vegvesen.no/dokumentasjon/
    title:
      en: NINA catalog for NVDB data
    url: https://example.org
  license:
    name: NLOD 1.0
    url: https://data.norge.no/nlod/no/1.0/
  provider:
    name: "Statens Vegvesen via NINA milj\xF8data"
    url: https://nvdbapiles-v3.atlas.vegvesen.no/dokumentasjon/
resources: {}
server:
  bind:
    host: 0.0.0.0
    port: 5000
  encoding: utf-8
  gzip: false
  languages:
  - en-US
  limit: 100
  map:
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap
      contributors</a>'
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
  mimetype: application/json; charset=UTF-8
  pretty_print: true
  url: ???
